const listOfAllowedRecipe = [
  'sushi',
  'fettuccine alfredo',
  'ratatouille',
  'french omelette',
  'jamaican beef patties',
  'mince pies',
  'poutine',
  'chicken karaage',
  'creamy tomato soup',
  'chicken congee',
  'beef wellington',
  'big mac',
  'beef rendang',
  'french onion soup',
  'nasi lemak',
  'pancakes',
  'shawarma',
  'wontons',
  'tonkatsu pork',
];
